using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

namespace hwfc
{
/// <summary>
/// Used for the world map generated by the single layer WFC.
/// </summary>

[CreateAssetMenu(menuName = "SO/Preplacements/WorldMapSingleWFC")]
public class WorldMapSinglewfc : Preplacement
{
    public override void Run(OverlapWFC wfc)
    {
        Fill(wfc, GeneratePattern(1, 3));

        var p = GeneratePattern(3, wfc.N);
        wfc.predetermined.Clear();

        // Place water
        // wfc.predetermined.Add(new Predetermined(wfc.width * wfc.depth / 2, GeneratePattern(1, 3)));

        // Use village instead of grass, values for different seeds might need to be adjusted
        // p = new byte[]
        // {
        //     3, 3, 3,
        //     3, 11, 11,
        //     3, 11, 11
        // };

        wfc.predetermined.Add(new Predetermined(wfc.width * wfc.depth / 2 + wfc.width / 2, p));
    }

    byte[] GeneratePattern(int value, int N)
    {
        byte[] ret = new byte[N * N];

        for (var i = 0; i < ret.Length; i++)
            ret[i] = (byte)value;

        return ret;
    }

    private void Fill(BaseWFC wfc, byte[] pattern)
    {
        wfc.predetermined = new List<Predetermined>();

        for (int i = 0; i < wfc.width; i++)
            wfc.predetermined.Add(new Predetermined(wfc.width * (wfc.depth - 1) + i, pattern));
    }
}
}
